FROM openjdk:11
ARG PROFILE
ARG DB_USER
ARG DB_PASSWORD
ARG ALLOWED_ORIGIN
ENV ALLOWED_ORIGIN $ALLOWED_ORIGIN
ENV DB_USER $DB_USER
ENV DB_PASSWORD $DB_PASSWORD
ENV PROFILE $PROFILE
WORKDIR /app
COPY ./build/libs/server-1.0.0.jar ./
COPY ./scripts/ ./
EXPOSE 8080 8888
CMD ./start.sh